apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-deployment
  labels:
    app: rabbit
  annotations:
    description: "Deployment do RabbitMQ"
    maintainer: "Hugo e Guilherme"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: masstransit/rabbitmq
        ports:
        - containerPort: 15672 # RabbitMQ management interface
        - containerPort: 5672  # RabbitMQ messaging port
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "admin" # rabbit username
        - name: RABBITMQ_DEFAULT_PASS
          value: "admin" # rabbit password
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
  - name: port1
    protocol: TCP
    port: 15672       # Service port for RabbitMQ management
    targetPort: 15672 # Container's port
    nodePort: 30002   # External port
  - name: port2
    protocol: TCP
    port: 5672        # Service port for RabbitMQ messaging
    targetPort: 5672  # Container's port
